self.solver_options = SolverOptions()
        self.solver_options.SetOption(self.osqp.solver_id(), "rho", 1e-03)
        self.solver_options.SetOption(self.osqp.solver_id(), "eps_abs", 1e-06)
        self.solver_options.SetOption(self.osqp.solver_id(), "eps_rel", 1e-06)
        self.solver_options.SetOption(self.osqp.solver_id(), "eps_prim_inf", 1e-06)
        self.solver_options.SetOption(self.osqp.solver_id(), "eps_dual_inf", 1e-06)
        self.solver_options.SetOption(self.osqp.solver_id(), "max_iter", 3000)
        self.solver_options.SetOption(self.osqp.solver_id(), "polish", True)
        self.solver_options.SetOption(self.osqp.solver_id(), "polish_refine_iter", 3)
        self.solver_options.SetOption(self.osqp.solver_id(), "warm_start", True)
        self.solver_options.SetOption(self.osqp.solver_id(), "verbose", False)